### ISSUE TITLE
Building with rosmake

### ISSUE THREAD

**Issue by mirellameelo** [x1597275/LSD-SLAM-with-ubuntu1804-and-melodic#1]
Hi. Tks for sharing!

EDIT: step-by-step

```hl
mkdir ~/rosbuild_ws 
cd ~/rosbuild_ws 
rosws init ./opt/ros/melodic  

rosws set ~/rosbuild_ws/package_dir -t . 
echo "source ~/rosbuild_ws/setup.bash" >> ~/.bashrc bash 

mkdir package_dir
cd package_dir 
git clone https://github.com/x1597275/LSD-SLAM-with-ubuntu1804-and-melodic.git lsd_slam

cd /usr/lib/x86_64-linux-gnu 
sudo ln -s libQGLViewer-qt4.so libQGLViewer.so.

rosmake lsd_slam
```

It has been building for almost 4 hours! I just gave up waiting. Is it expected to take that long?

Tks in advance. 

**[ rosmake ] [ make ] [ lsd_slam_viewer: 13468.1 sec ]                          [ 1 Active 48/50 Complete ]**

**Comment by x1597275** [comment]
if there are no errors

> Hi. Tks for sharing!
> 
> EDIT: step-by-step
> 
> ```
> mkdir ~/rosbuild_ws 
> cd ~/rosbuild_ws 
> rosws init ./opt/ros/melodic  
> 
> rosws set ~/rosbuild_ws/package_dir -t . 
> echo "source ~/rosbuild_ws/setup.bash" >> ~/.bashrc bash 
> 
> mkdir package_dir
> cd package_dir 
> git clone https://github.com/x1597275/LSD-SLAM-with-ubuntu1804-and-melodic.git lsd_slam
> 
> cd /usr/lib/x86_64-linux-gnu 
> sudo ln -s libQGLViewer-qt4.so libQGLViewer.so.
> 
> rosmake lsd_slam
> ```
> 
> It has been building for almost 4 hours! I just gave up waiting. Is it expected to take that long?
> 
> Tks in advance.
> 
> **[ rosmake ] [ make ] [ lsd_slam_viewer: 13468.1 sec ] [ 1 Active 48/50 Complete ]**

If there are no errors,maybe your computer is slow,i use a double system not a virtual machine.

**Comment by rajk97** [comment]
@mirellameelo , were you able to complete make? It's taking a lot of time for me as well. Any hacks that made it faster for you? Please comment.

**Comment by mirellameelo** [comment]
Hi. Try this branch (It workded for me): https://github.com/kevin-george/lsd_slam

**Comment by rajk97** [comment]
Thanks for sharing this. Could you please tell me if this takes hours as well? Did you make any additional changes for using https://github.com/kevin-george/lsd_slam with ROS-Melodic?

**Comment by mirellameelo** [comment]
You're welcome! 
I think it didn't take even 5 minutes. I don't record of making any change to build it.

**Comment by rajk97** [comment]
Thank you!
